force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>Post-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/Image_Path__c.field-meta.xml
<CustomField>
    <fullName>Image_Path__c</fullName>
    <label>Image Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Is_Image_Attached__c.field-meta.xml
<CustomField>
    <fullName>Is_Image_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Image Attached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Likes_Count__c.field-meta.xml
<CustomField>
    <fullName>Likes_Count__c</fullName>
    <label>Likes Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Post_Owner__c.field-meta.xml
<CustomField>
    <fullName>Post_Owner__c</fullName>
    <label>Post Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Post_User__c.field-meta.xml
<CustomField>
    <fullName>Post_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post User</label>
    <referenceTo>User_Login_Detail__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyNewWorkplaceApp_CrtePstApexController.cls
public class MyNewWorkplaceApp_CrtePstApexController {

    //class to hold file related data
    public class relatedFile {
        public String PathOnClient;
        public String Title;
        public Blob VersionData;
    }
            
    @AuraEnabled
    public static void savePost(string message, string userName, string userId, List<Map<String, Object>> files){

        System.debug('Number of image uploaded : ' + files.size());
        string imageId = '';
        List<ContentVersion> images = new List<ContentVersion>();
        for (Map<String, Object> file : files) {

            String fileJson = JSON.serialize(file);
            relatedFile relatedDocument = (relatedFile) JSON.deserialize(fileJson, relatedFile.class);

            ContentVersion contentVersionFile = new ContentVersion();
            contentVersionFile.PathOnClient = relatedDocument.PathOnClient;
            contentVersionFile.Title = relatedDocument.Title;
            contentVersionFile.VersionData = relatedDocument.VersionData;
            images.add(contentVersionFile);

            System.debug('PathOnClient : ' + relatedDocument.PathOnClient);
            System.debug('Title : ' + relatedDocument.Title);

            Database.saveResult saveResult = Database.insert(images[0]);
            imageId = saveResult.getId();
        }

        System.debug('File id is : ' + imageId);
        system.debug(message);
        system.debug(userName);
        system.debug(userId);
        
        Post__c newPost = new Post__c();
        newPost.Post_Owner__C = userName;
        newPost.Post_User__c = userId;

        if(!String.isBlank(message)){
            newPost.Message__c = message; 
        }
        else {
            newPost.Message__c = ' ';
        }
         
        newPost.Likes_Count__c = 0;
        
       if(!String.isBlank(imageId) || !String.isEmpty(imageId)){
                       
            newPost.Is_Image_Attached__c = true;
            newPost.Image_Path__c =  'https://yashmah16workplace-dev-ed--c.documentforce.com/' + 
                                      'sfc/servlet.shepherd/version/download/'+ imageId;   
            System.debug(newPost.Image_Path__c);    
        }               
        else{
            newPost.Is_Image_Attached__c = false;
            newPost.Image_Path__c = ''; 
        } 
        insert newPost;
    }
}