force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>Post-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/Comments_Count__c.field-meta.xml
<CustomField>
    <fullName>Comments_Count__c</fullName>
    <label>Comments Count</label>
    <summaryForeignKey>Comment__c.Post__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Likes_Count__c.field-meta.xml
<CustomField>
    <fullName>Likes_Count__c</fullName>
    <label>Likes Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Post_Owner__c.field-meta.xml
<CustomField>
    <fullName>Post_Owner__c</fullName>
    <label>Post Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MyNewWorkplaceApp_TrendingApexContrller.cls
public class MyNewWorkplaceApp_TrendingApexContrller {    
    
    @AuraEnabled(cacheable=true)
    public static List<Post__c> fetchTrendingPosts(){
        
        System.debug('fetching data');
        List<Post__c> allPosts = new List<Post__c>();
        allPosts = [SELECT Id, Name, Message__c, Likes_Count__c, Comments_Count__c, Post_Owner__c
                    From Post__c
                    ORDER BY Likes_Count__c DESC
                    LIMIT 5];

        System.debug(allPosts.size());
        return allPosts;
    }
}