force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment_Message__c.field-meta.xml
<CustomField>
    <fullName>Comment_Message__c</fullName>
    <label>Comment Message</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Comment_User__c.field-meta.xml
<CustomField>
    <fullName>Comment_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comment User</label>
    <referenceTo>User_Login_Detail__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comment_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Likes__c/Likes__c.object-meta.xml
<CustomObject>
    <label>Like</label>
    <nameField>
        <displayFormat>Like-{0000}</displayFormat>
        <label>Like number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Likes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Likes__c/fields/Liked_by_Id__c.field-meta.xml
<CustomField>
    <fullName>Liked_by_Id__c</fullName>
    <label>Liked by Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Likes__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Likes</relationshipLabel>
    <relationshipName>Likes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>Post-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/Is_Liked_By_Current_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Liked_By_Current_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Liked By Current User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Like_Old_value__c.field-meta.xml
<CustomField>
    <fullName>Like_Old_value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Like Old value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Likes_Count__c.field-meta.xml
<CustomField>
    <fullName>Likes_Count__c</fullName>
    <label>Likes Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Login_Detail__c/User_Login_Detail__c.object-meta.xml
<CustomObject>
    <label>User Login Detail</label>
    <nameField>
        <displayFormat>UWP-{00}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserLoginDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Login_Detail__c/fields/Is_Current_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Login_Detail__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Will be used for login purpose</description>
    <formula>Last_Name__c + &apos; , &apos; +  First_Name__c</formula>
    <label>User Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MyNewWorkplaceApp_UpdatePostController.cls
public class MyNewWorkplaceApp_UpdatePostController {

    @AuraEnabled
    public static void UpdateSinglePostData(string recordId, boolean isDisliked){

        System.debug(recordId);

        User_Login_Detail__c currentUser = [SELECT Id, User_Name__c
                                            FROM User_Login_Detail__c
                                            WHERE Is_Current_User__c = true]; 

        string currentUserId = currentUser.Id;
        system.debug('Is post disliked ? : ' + isDisliked);
        
        if(isDisliked == false){

            Likes__c newLike = new Likes__c();
            newLike.Liked_by_Id__c = currentUserId;	
            newLike.Post__c = recordId;
            
            insert newLike;   
                  
            Post__C oldPost = [SELECT Id, Likes_Count__c, Is_Liked_By_Current_User__c, Like_Old_value__c 
                                FROM Post__c
                                WHERE Id =: recordId];
            
            oldPost.Likes_Count__c = oldPost.Likes_Count__c + 1;
            oldPost.Is_Liked_By_Current_User__c = true;
            oldPost.Like_Old_value__c = true;
            
            update oldPost;
        }
        else{
            system.debug('Is post disliked ? : ' + isDisliked);
            system.debug('User id is : ' + currentUserId);
            system.debug('Record id is : ' + recordId);

            List<Likes__c> oldLike = [SELECT Id 
                                FROM Likes__c
                                WHERE Liked_by_Id__c =: currentUserId
                               	AND Post__c =: recordId];            
            
            delete oldLike;   
                  
            Post__C oldPost = [SELECT Id, Likes_Count__c, Is_Liked_By_Current_User__c, Like_Old_value__c 
                                FROM Post__c
                                WHERE Id =: recordId];
            
            oldPost.Likes_Count__c = oldPost.Likes_Count__c - 1;
            oldPost.Is_Liked_By_Current_User__c = false;
            oldPost.Like_Old_value__c = false;
            
            update oldPost;
        }
    }

    @AuraEnabled
    public static void UpdateCommentsData(string recordId, string message, string currentuserid){

        System.debug(currentuserid);
        Comment__c newComment = new Comment__c();
        newComment.Comment_Message__c = message;
        newComment.Post__c = recordId;
        newComment.Comment_User__c = currentuserid;

        insert newComment;
    }
}