force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment_Message__c.field-meta.xml
<CustomField>
    <fullName>Comment_Message__c</fullName>
    <label>Comment Message</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Comment_User__c.field-meta.xml
<CustomField>
    <fullName>Comment_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comment User</label>
    <referenceTo>User_Login_Detail__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comment_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Relative_Time__c.field-meta.xml
<CustomField>
    <fullName>Relative_Time__c</fullName>
    <formula>IF(
NOW() - CreatedDate &gt; 0 ,
TEXT( FLOOR( NOW() - CreatedDate ) ) &amp; &quot; days &quot;
&amp; TEXT( FLOOR( MOD( (NOW()- CreatedDate ) * 24, 24 ) ) ) &amp; &quot; hours &quot;
&amp; TEXT( ROUND( MOD( (NOW()- CreatedDate ) * 24 * 60, 60 ), 0 ) ) &amp; &quot; minutes&quot;,
&quot;Just now&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Relative Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Likes__c/Likes__c.object-meta.xml
<CustomObject>
    <label>Like</label>
    <nameField>
        <displayFormat>Like-{0000}</displayFormat>
        <label>Like number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Likes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Likes__c/fields/Liked_by_Id__c.field-meta.xml
<CustomField>
    <fullName>Liked_by_Id__c</fullName>
    <label>Liked by Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Likes__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Likes</relationshipLabel>
    <relationshipName>Likes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>Post-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/Comments_Count__c.field-meta.xml
<CustomField>
    <fullName>Comments_Count__c</fullName>
    <label>Comments Count</label>
    <summaryForeignKey>Comment__c.Post__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Image_Path__c.field-meta.xml
<CustomField>
    <fullName>Image_Path__c</fullName>
    <label>Image Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Is_Image_Attached__c.field-meta.xml
<CustomField>
    <fullName>Is_Image_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Image Attached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Is_Liked_By_Current_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Liked_By_Current_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Liked By Current User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Like_Old_value__c.field-meta.xml
<CustomField>
    <fullName>Like_Old_value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Like Old value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Likes_Count__c.field-meta.xml
<CustomField>
    <fullName>Likes_Count__c</fullName>
    <label>Likes Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Post_Owner__c.field-meta.xml
<CustomField>
    <fullName>Post_Owner__c</fullName>
    <label>Post Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Post_User__c.field-meta.xml
<CustomField>
    <fullName>Post_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post User</label>
    <referenceTo>User_Login_Detail__c</referenceTo>
    <relationshipLabel>Posts</relationshipLabel>
    <relationshipName>Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Relative_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Relative_Datetime__c</fullName>
    <formula>IF(
   NOW() -  CreatedDate &gt; 0 ,
  TEXT( FLOOR( NOW() - CreatedDate ) ) &amp; &quot; days &quot;
  &amp; TEXT( FLOOR( MOD( (NOW()- CreatedDate ) * 24, 24 ) ) ) &amp; &quot; hours &quot;
  &amp; TEXT( ROUND( MOD( (NOW()- CreatedDate ) * 24 * 60, 60 ), 0 ) ) &amp; &quot; minutes&quot;,
  &quot;Just now&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Relative Datetime</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Login_Detail__c/User_Login_Detail__c.object-meta.xml
<CustomObject>
    <label>User Login Detail</label>
    <nameField>
        <displayFormat>UWP-{00}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserLoginDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Login_Detail__c/fields/Is_Profile_Pic_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Profile_Pic_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Profile Pic Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Login_Detail__c/fields/Profile_Picture_Path__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture_Path__c</fullName>
    <label>Profile Picture Path</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Login_Detail__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Will be used for login purpose</description>
    <formula>Last_Name__c + &apos; , &apos; +  First_Name__c</formula>
    <label>User Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Workplace_MyPostsController.cls
public with sharing class Workplace_MyPostsController {

    public Workplace_MyPostsController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Post__c> getMyPosts(string userId){

      System.debug('Current user is : ' + userId);
        
      List<Post__c> myPosts = new List<Post__c>();
      myPosts = [SELECT Id, Name, Message__c, Relative_Datetime__c, Post_Owner__c, Is_Image_Attached__c,
                          Like_Old_value__c, Likes_Count__c, Comments_Count__c, 
                          Is_Liked_By_Current_User__c, Image_Path__c, Post_User__r.Profile_Picture_Path__c,
                          Post_User__r.Is_Profile_Pic_Uploaded__c,
                          (SELECT Liked_by_Id__c 
                              FROM Likes__r 
                              WHERE Liked_by_Id__c =: userId),
                          (SELECT Id, Comment_Message__c, Comment_User__r.User_Name__c, Relative_Time__c 
                              FROM Comments__r 
                              ORDER BY CreatedDate DESC)
                  FROM Post__c
                  WHERE Post_User__r.Id =: userId
                  ORDER BY CreatedDate DESC];
      
      for(Post__c post: myPosts){
                    
          List<string> userIds = new List<string>();
          for(Likes__c likedBy: post.Likes__r){              
              userIds.add(likedBy.Liked_by_Id__c);                
          }            
          
          if(userIds.contains(userId))
              post.Like_Old_value__c = true;
          else
              post.Like_Old_value__c = false;
      }
      return myPosts;  

    }

    @AuraEnabled
    public static void deletePost(string postId){
      try {

        Post__c postToBeDeleted = [SELECT Id, Name
                                    FROM Post__c 
                                    WHERE Id =: postId];

        delete postToBeDeleted;
        
      } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
      }
    }
}